export const projects = [
  {
    title: 'Social Media Platform',
    description: "A social media platform with private messaging system developed with React front-end, Node.js back-end, and MySQL database hosted by AWS. Developed with goal of encouraging social practice among musicians.",
      image: '/images/proj1.png',
      tags: ['React', 'Node', 'MySQL', 'AWS'],
    source: 'https://github.com/NoalGesler/WeShed',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Unix Shell with FAT32 File Sytem',
    description:"Mock Unix shell developed with C in a Unix environment. Tokenizes user input to replicate a variety of the most common bash commands. FAT32 File System performs read/write functions given a valid image file.",
    image: '/images/proj2.png',
    tags: ['C/C++', 'Unix'],
    source: 'https://github.com/NoalGesler/Unix-Shell-and-FAT32-File-System',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Encrypted P2P Messenger',
    description: "Encrypted messenger that uses I/O socket connection to connect participants. Messages are encrypted with 128-bit AES algorithm with MD5 hash. Developed with Python, JavaScript, and HTML",
      image: '/images/proj3.png',
      tags: ['Python', 'JavaScript', 'HTML'],
    source: 'https://github.com/NoalGesler/Encrypted-P2P-Messenger',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Discord Bots',
    description: "Freelance work creating custom Discord bots and delivering them to clients based on their specifications. Examples include music bots and countdown bots. Due to the nature of selling this software, source code is not available.",
    image: '/images/proj4.jpg',
    tags: ['Java', 'Discord API', 'Firebase'],
    source: '#projects',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Personal Portfolio Webapp',
    description: "This very website was developed with React and serves as a portfolio for my journey in the field of Software Engineering. Source Code, like every other project, is available below",
    image: '/images/proj5.png',
    tags: ['JavaScript', 'React', 'HTML/CSS'],
    source: 'https://github.com/NoalGesler/Noal-Gesler-Portfolio-Webapp',
    visit: 'https://google.com',
    id: 4,
  },
];
